const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=__dirname;
const queries={
 overview:`customEvents | where timestamp > ago(7d) | summarize visitors=dcount(tostring(customDimensions.visitor)), activeDevices=dcountif(tostring(customDimensions.visitor),name == 'board_enter'), activeBoards=dcountif(tostring(customDimensions.board),name == 'board_enter'), createdBoards=countif(name == 'board_created')`,
 daily:`customEvents | where timestamp > ago(7d) | summarize visitors=dcount(tostring(customDimensions.visitor)), entries=countif(name == 'board_enter') by day=bin(timestamp,1d) | order by day asc`,
 boards:`customEvents | where timestamp > ago(7d) | extend board=tostring(customDimensions.board) | where board != '' | summarize visitors=dcountif(tostring(customDimensions.visitor),name == 'board_enter'), entries=countif(name == 'board_enter'), actions=countif(name == 'module_action'), successes=countif(name == 'module_success') by board | order by visitors desc | take 100`,
 modules:`customEvents | where timestamp > ago(7d) | extend module=tostring(customDimensions.module) | where module != '' | summarize views=dcountif(tostring(customDimensions.visitor),name == 'module_view'), participants=dcountif(tostring(customDimensions.visitor),name == 'module_action'), actions=countif(name == 'module_action'), successes=countif(name == 'module_success') by module | order by views desc`
};
let cached,token,loading;
function authorized(req){if(process.env.METRICS_AUTH_MODE!=='azure'||!process.env.METRICS_OWNER_ID)return false;try{const p=JSON.parse(Buffer.from(req.headers['x-ms-client-principal']||'','base64').toString());return p.auth_typ==='aad'&&p.claims?.some(c=>['http://schemas.microsoft.com/identity/claims/objectidentifier','oid'].includes(c.typ)&&c.val===process.env.METRICS_OWNER_ID)}catch{return false}}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data))}
async function accessToken(){if(token&&token.until>Date.now()+60000)return token.value;if(!process.env.IDENTITY_ENDPOINT||!process.env.IDENTITY_HEADER)throw Error('Identity not configured');const u=new URL(process.env.IDENTITY_ENDPOINT);u.searchParams.set('resource','https://api.applicationinsights.io');u.searchParams.set('api-version','2019-08-01');const r=await fetch(u,{headers:{'X-IDENTITY-HEADER':process.env.IDENTITY_HEADER},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('Identity unavailable');const d=await r.json();if(!d.access_token)throw Error('Identity unavailable');token={value:d.access_token,until:Number(d.expires_on)*1000};return token.value}
async function metrics(){if(cached&&Date.now()-cached.time<60000)return cached.data;if(loading)return loading;loading=(async()=>{if(!/^[a-f0-9-]{36}$/i.test(process.env.METRICS_APP_ID||''))throw Error('Metrics not configured');const t=await accessToken();const results=await Promise.all(Object.entries(queries).map(async([name,query])=>{const r=await fetch('https://api.applicationinsights.io/v1/apps/'+process.env.METRICS_APP_ID+'/query',{method:'POST',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},body:JSON.stringify({query}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Query unavailable');const d=await r.json();if(d.error||!d.tables?.[0])throw Error('Query unavailable');const table=d.tables[0];return [name,table.rows.map(row=>Object.fromEntries(table.columns.map((c,i)=>[c.name,row[i]])))]}));const data={...Object.fromEntries(results),updatedAt:new Date().toISOString()};cached={time:Date.now(),data};return data})();try{return await loading}finally{loading=null}}
http.createServer(async(req,res)=>{let u;try{u=new URL(req.url,'http://localhost')}catch{return json(res,400,{error:'请求无效'})}
 if(u.pathname==='/api/metrics'){if(req.method!=='GET')return json(res,405,{error:'Method not allowed'});if(!authorized(req))return json(res,401,{error:'请用管理员账号登录',loginReady:process.env.METRICS_AUTH_MODE==='azure'&&!!process.env.METRICS_OWNER_ID});try{return json(res,200,await metrics())}catch{return json(res,503,{error:'统计暂时无法读取，请稍后重试'})}}
 if(!['GET','HEAD'].includes(req.method))return json(res,405,{error:'Method not allowed'});
 let name;const match=/^\/([A-Za-z0-9]{4,16})(\/?)$/.exec(u.pathname);
 if(match&&!match[2]){res.writeHead(301,{Location:u.pathname+'/'+u.search});return res.end()}
 if(u.pathname==='/')name='index.html';else if(u.pathname==='/metrics/')name='metrics/index.html';else if(u.pathname==='/qjdy/')name='qjdy/index.html';else if(/^\/(?:assets|qjdy\/assets)\/[A-Za-z0-9_.-]+$/.test(u.pathname))name=u.pathname.slice(1);else if(match&&!['assets','qjdy','metrics'].includes(match[1]))name='index.html';
 if(!name||!fs.existsSync(path.join(root,name))){res.writeHead(404);return res.end('Not found')}
 const data=fs.readFileSync(path.join(root,name));const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.css':'text/css'}[path.extname(name)]||'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Content-Length':data.length,'Cache-Control':mime.startsWith('text/html')?'no-cache':'public, max-age=3600','X-Content-Type-Options':'nosniff'});res.end(req.method==='HEAD'?undefined:data);
}).listen(Number(process.env.PORT||8080),'0.0.0.0');
